name: Videos Fetch

on:
  workflow_dispatch:

jobs:
  update-videos-streams:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT_HUKAMNAMA: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUKAMNAMA }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin google-cloud-firestore
          pip install requests firebase-admin beautifulsoup4

      
      - name: 🛕 Run Harmandir Sahib Hukamnama Fetch
        env:
          FIREBASE_SERVICE_ACCOUNT_GURBANI: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GURBANI }}
          FIREBASE_SERVICE_ACCOUNT_HARMANDIR: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HARMANDIR }}
          FIREBASE_SERVICE_ACCOUNT_HUKAMNAMA: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUKAMNAMA }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python videos-fetch/Harmandir-Sahib-Hukamnama.py

      - name: 🛕 Run Harmandir Sahib Hukamnama Katha Fetch
        env:
          FIREBASE_SERVICE_ACCOUNT_GURBANI: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GURBANI }}
          FIREBASE_SERVICE_ACCOUNT_HARMANDIR: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HARMANDIR }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python videos-fetch/Harmandir-Sahib-Hukamnama-Katha.py

      - name: 🛕 Run Hazur Sahib Hukamnama Fetch
        env:
          FIREBASE_SERVICE_ACCOUNT_GURBANI: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GURBANI }}
          FIREBASE_SERVICE_ACCOUNT_HARMANDIR: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HARMANDIR }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python videos-fetch/Hazur-Sahib-Hukamnama.py
